### PR TITLE
sliding cards project added

### PR DESCRIPTION
**Pull request by Janhvi52**
closes issue #74 

The project us sliding cards i.e. upon clicking the card it'll get slided automatically and only one card at a time can be viewed to it's full height and width, this feature is added using javascript and added css for styling with the html structure.
You can refer the ss attached below

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Screenshot (101)

Hope you'll like it!

### CODE REVIEW

**Comment by utkarsh006** [comment]
Complete the checkboxes like this [x]

**Comment by utkarsh006** [comment]
Add comments and README file too.

**Comment by Janhvi52** [comment]
> Add comments and README file too.

Hey you can check now!

**Comment by utkarsh006** [comment]
LGTM ⭐ 
- Feedback : Next time onwards, Try to give meaningful name to your branch.

**Comment by Janhvi52** [comment]
> LGTM ⭐ 
> - Feedback : Next time onwards, Try to give meaningful name to your branch.

sure! Thanks for your valuable feedback

**Pull request merged**
