### PR TITLE
Guess the number

### PR DESCRIPTION
**Pull request by Pinkuagrawal28**
## Related Issue
 
I was assigned the project Guess The Number with issue number #96 .

### Describe Changes

I have added all the files and also added the readme file.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

Screenshot (382)
Screenshot (384)
Screenshot (386)
Screenshot (387)

### CODE REVIEW

**Comment by Pinkuagrawal28** [comment]
@Shweta2024 @utkarsh006  please review my pr.

**Review by Shweta2024 — CHANGES_REQUESTED** [review]
add a Working Video in the README.md

**Review by Shweta2024 — CHANGES_REQUESTED** [review]
add proper comments in the script.js file.

**Comment by Pinkuagrawal28** [comment]
@Shweta2024  didi Done.

**Review by Shweta2024 — APPROVED** [review]

**Comment by Shweta2024** [comment]
LGTM🎉

**Pull request merged**
