### PR TITLE
Resize and compress images app issue #64

### PR DESCRIPTION
**Pull request by shaunak-09**
## Related Issue
Resize and compress images app (Issue #64)

### Describe Changes
In this application we can upload any image and then we can change the width and height of the image as per choice. We can even reduce the quality of the image and then download this image.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### CODE REVIEW

**Comment by shaunak-09** [comment]
SCREENSHOT
Screenshot 2022-12-20 040439

**Comment by utkarsh006** [comment]
@shaunak-09 Mention issue number and tick the checkboxes.

**Comment by shaunak-09** [comment]
Done

**Comment by Shweta2024** [comment]
> Done

@shaunak-09 tickmark the checkboxes like this [x]

**Comment by shaunak-09** [comment]
Done

**Comment by utkarsh006** [comment]
Follow Guideline 4

**Pull request closed without merging**
