### PR TITLE
Beginners Start project

### PR DESCRIPTION
**Pull request by KrishGaur1354**
## Related Issue
 
Created a Beginner Start project where beginners can learn to create education web app. Issue #128 

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

Screenshot (288)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@KrishGaur1354 Mention issue number.

**Comment by KrishGaur1354** [comment]
> @KrishGaur1354 Mention issue number.

Issue #128

**Comment by utkarsh006** [comment]
@KrishGaur1354 Do as I mentioned.

**Comment by Shweta2024** [comment]
> > @KrishGaur1354 Mention issue number.
> 
> Issue #128

@KrishGaur1354 the issue isn't assigned to you.You can't create a pr until the issue is assigned to you.

**Comment by Shweta2024** [comment]
> > > @KrishGaur1354 Mention issue number.
> > 
> > 
> > Issue #128
> 
> @KrishGaur1354 the issue isn't assigned to you.You can't create a pr until the issue is assigned to you.

@utkarsh006 there are no responses to the messages, also the issue wasn't assigned to him. I'm closing the pr.

**Pull request closed without merging**
