### PR TITLE
Updated index.html

### PR DESCRIPTION
**Pull request by SattyamSamania**
## Related Issue
 
Replace text input with drop-down menu #1

### Describe Changes

Updated index.html file in Weather-App Folder

### Checklist

- [x ] ✅ My code follows the code style of this project.
- [x ] 🚩 All new and existing tests passed.
- [x ] 🌟 I have starred the repo
- [x ] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

Screenshot (260)

### CODE REVIEW

**Comment by Shweta2024** [comment]
image
please remove the text input.
And don't use any random city names, because it's not showing the temperature for all of them. Test your code once its throwing an error on submitting the city name.
Use only 20 cities that will be enough and do test before creating the pr that if its showing the temperatures for those cities or not.

**Comment by Shweta2024** [comment]
> > image please remove the text input. And don't use any random city names, because it's not showing the temperature for all of them. Test your code once its throwing an error on submitting the city name. Use only 20 cities that will be enough and do test before creating the pr that if its showing the temperatures for those cities or not.
> 
> Am I doing something wrong if no city is showing the weather?

I tried out for a few cities and it wasn't giving the result.
Also, the task was to replace the text input with the drop-down menu, but you haven't removed the text input, kindly remove the text input.
Just take a few cities, you can take 20 cities and try out with them in Postman if they are giving results.

**Comment by Shweta2024** [comment]
@SattyamSamania remove line number 233 of the index.html,in order to remove the text input box.
Also, in line number 14, write id as cityInput and name as cityName.
After doing the above changes it will work.

**Comment by SattyamSamania** [comment]
> @SattyamSamania remove line number 233 of the index.html,in order to remove the text input box.
> Also, in line number 14, write id as cityInput and name as cityName.
> After doing the above changes it will work.

Hey @Shweta2024 I have made changes of id and name and removed the text input. But I am not able to check the cities weather. Please guide me how to check weather for particular cities. As I don't know much about APIs. If that gets resolved I will definitely make PR with all the changes. Thank you !

**Comment by SattyamSamania** [comment]
> > > @SattyamSamania remove line number 233 of the index.html,in order to remove the text input box.
> > > Also, in line number 14, write id as cityInput and name as cityName.
> > > After doing the above changes it will work.
> > 
> > Hey @Shweta2024 I have made changes of id and name and removed the text input. But I am not able to check the cities weather. Please guide me how to check weather for particular cities. As I don't know much about APIs. If that gets resolved I will definitely make PR with all the changes. Thank you !
> 
> Join the [Discord Channel](http://discord.openinapp.co/discord-1-10390) and ping me there. I'll get back to you.

Sure. Joined

**Comment by utkarsh006** [comment]
@SattyamSamania Do complete the PR template properly.

**Comment by SattyamSamania** [comment]
> @SattyamSamania Do complete the PR template properly.

Sure. Right now I am working on this.

**Comment by utkarsh006** [comment]
@SattyamSamania What's the update?

**Pull request closed without merging**
