### PR TITLE
Signup31

### PR DESCRIPTION
**Pull request by Riya14-dangra**
## Related Issue
 
* Add login signup page  #31 

### Describe Changes

* I have made a login signup page in which new user can signup in its account and the user already having account can do login and check their previous activities

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
* HTML code(to give the skeleton to our web page)

Screenshot (99)

* CSS code (to make UI more attractive)

Screenshot (100)

* JS code(just adding a toggle function)
Screenshot (101)

* OUTPUT of the code

https://user-images.githubusercontent.com/84792579/206900709-8dd35235-9830-4b76-a12b-f7120c5a5548.mp4

Hope You like it!!
Thank you:)

### CODE REVIEW

**Comment by Riya14-dangra** [comment]
@utkarsh006 is it correct now please have a look

**Comment by utkarsh006** [comment]
@Riya14-dangra If you raising 2 PR's for a single issue, close the one which you don't want to be reviewed.

**Comment by utkarsh006** [comment]
@Riya14-dangra Where's the README folder inside your project?

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra If you raising 2 PR's for a single issue, close the one which you don't want to be reviewed

Done I have closed the previous one

**Comment by utkarsh006** [comment]
> > @Riya14-dangra If you raising 2 PR's for a single issue, close the one which you don't want to be reviewed
> 
> Done I have closed the previous one

Attach the README folder following the guidelines and you are good to go.

**Comment by Riya14-dangra** [comment]
> > > @Riya14-dangra If you raising 2 PR's for a single issue, close the one which you don't want to be reviewed
> > 
> > 
> > Done I have closed the previous one
> 
> Attach the README folder following the guidelines and you are good to go.

Can you please explain how to attached it

**Comment by Riya14-dangra** [comment]
I have added a comments properly everywhere in the code and while making the PR I explained everything should I need to add the redme again if yes then please explain how?

**Comment by utkarsh006** [comment]
@Riya14-dangra Refer the guidelines.

**Comment by Shweta2024** [comment]
> I have added a comments properly everywhere in the code and while making the PR I explained everything should I need to add the redme again if yes then please explain how to add it?

@Riya14-dangra 
In your project folder create a file and name it as: README.md.
In that file provide all the required details according to the contributing guidelines.

**Comment by Riya14-dangra** [comment]
@utkarsh006 Please have a look
Thank you!!

**Comment by Riya14-dangra** [comment]
> @utkarsh006 Please have a look I have added README.md file Thank you!!



> @Riya14-dangra Add working video in README file.

@utkarsh006 done
Please have a look

**Comment by utkarsh006** [comment]
LGTM ⭐
@Shweta2024 Merge the PR.

**Pull request merged**
