### PR TITLE
Wallpaper generator

### PR DESCRIPTION
**Pull request by nikhilsrv**
## Related Issue
#68 

### Describe Changes
Added Wallpaper Generator

### Checklist
- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

Screenshot (484)
Screenshot (485)
Screenshot (486)

### CODE REVIEW

**Comment by nikhilsrv** [comment]
@Shweta2024 please review ,my pull request.

**Comment by nikhilsrv** [comment]
@utkarsh006 I have deleted other files.Please review

**Comment by utkarsh006** [comment]
@nikhilsrv Delete ping pong and tic tac toe files.

**Comment by nikhilsrv** [comment]
@utkarsh006 I have deleted it

**Comment by utkarsh006** [comment]
@nikhilsrv Add comments in HTML & JS code.

**Comment by utkarsh006** [comment]
LGTM ⭐ Nice Work !

**Pull request merged**
