### PR TITLE
Adding Grocery-List project

### PR DESCRIPTION
**Pull request by Suryansh1720001**
Hello @utkarsh006 @Shweta2024 
**I added the Grocery List project of Java script. Let's use our grocery list to go supermarket shopping. You may keep a list of the things you need to buy using this wonderful software, you only need to add the items here. Additionally, you have the option of removing any unnecessary things.**

## Related Issue 
Issue no. #140
Project name- Grocery List

## Describe Changes
✅ Added the project
✅ Added the comments 
✅ Read the Contributing Guideline
✅ I have starred the repo
✅ Added the Demo video in the Readme file

## Screenshot
image

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Suryansh1720001 Good work ⭐ Attach the video here that you have mentioned in README file.

**Comment by Suryansh1720001** [comment]
# Demo video of Grocery List 
https://user-images.githubusercontent.com/85965606/209615076-ec2b469d-c611-4256-afcf-a9a898d6ff02.mp4


Hello @utkarsh006,
I have added the demo video as you said. 
Thank you.

**Review by Shweta2024 — CHANGES_REQUESTED** [review]
list the Tech stack used in the README.md file

**Comment by Suryansh1720001** [comment]
@utkarsh006 @Shweta2024 
- [x] Tech Stack added in the readme file
Thank you

**Review by Shweta2024 — APPROVED** [review]

**Comment by Shweta2024** [comment]
@Suryansh1720001 great work!
LGTM🎉

**Pull request merged**
