### PR TITLE
calculator height increased to prevent buttons from flowing out

### PR DESCRIPTION
**Pull request by DHRUVKHANDELWAL00**
## Related Issue
To put buttons inside calculator #95
 

### Describe Changes
Increased the height of calculator block.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

image

### CODE REVIEW

**Comment by YashAw12** [comment]
@Shweta2024 @utkarsh006 
Describe changes you would make
I can make the calculator fully responsive on all screen sizes, this particular pr makes the button inside only on this particular size, it will fail when size is reduced, i can fix it. I have already commented in the open issue section, commenting again here!. Please assign it to me!
☑️ I follow the https://docs.github.com/articles/github-community-guidelines Github community guidelines.

**Comment by Shweta2024** [comment]
> @Shweta2024 @utkarsh006 Describe changes you would make I can make the calculator fully responsive on all screen sizes, this particular pr makes the button inside only on this particular size, it will fail when size is reduced, i can fix it. I have already commented in the open issue section, commenting again here!. Please assign it to me! ☑️ I follow the https://docs.github.com/articles/github-community-guidelines Github community guidelines.

create a new issue for that @YashAw12

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006 am i missing anything?

**Comment by Shweta2024** [comment]
@DHRUVKHANDELWAL00 your branch is having conflicts please resolve it.

**Comment by DHRUVKHANDELWAL00** [comment]
@Shweta2024 ok

**Comment by DHRUVKHANDELWAL00** [comment]
@Shweta2024 done

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Mention issue number.

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006  done.

**Pull request merged**
