### PR TITLE
Tic tac toe

### PR DESCRIPTION
**Pull request by nikhilsrv**
### **Related Issue**
#40 
### **Describe Changes:**
Added a Tic-Tac-Toe game website
### **Checklist**
- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)
### **What types of changes does your code introduce?**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### **Screenshots**
Screenshot (469)

Screenshot (470)

Screenshot (471)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@nikhilsrv You have removed the PR template completely. This is unacceptable. Complete it first.

**Comment by nikhilsrv** [comment]
@utkarsh006  I have edited the comment and added readme file.Is it fine?

**Comment by utkarsh006** [comment]
LGTM ⭐ 
@Shweta2024 Do Merge the PR.

**Comment by Shweta2024** [comment]
@nikhilsrv great work!
LGTM

**Pull request merged**
