### PR TITLE
Resize images

### PR DESCRIPTION
**Pull request by shaunak-09**
## Related Issue
Resize and compress images app (Issue #64)

### Describe Changes
In this application we can upload any image and then we can change the width and height of the image as per choice. We can even reduce the quality of the image and then download this image.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

SCREENSHOT
Screenshot 2022-12-20 040439

### CODE REVIEW

**Comment by utkarsh006** [comment]
Follow Guideline 5.

**Comment by shaunak-09** [comment]
Done

**Comment by utkarsh006** [comment]
@shaunak-09 Add video to your readme and remove the comment as mentioned above in review.

**Comment by Shweta2024** [comment]
> @shaunak-09 Add video to your readme and remove the comment as mentioned above in review.

@shaunak-09 follow the above instructions and do the required changes ASAP otherwise the pr will get closed & issue will be unassigned from you.

**Comment by shaunak-09** [comment]
Done. Sorry for the delay . I was out of station.

**Comment by utkarsh006** [comment]
@shaunak-09 Remove the comment which I have told you.

**Pull request closed without merging**
