### PR TITLE
Ludo Game added.

### LINKED ISSUE #71: Ludo Game
**Describe the changes you'd like**

Create a ludo game.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

### PR DESCRIPTION
**Pull request by Rishav1707**
## Related Issue
 
closes #71 

### Describe Changes

- Ludo Game file has been added.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

https://user-images.githubusercontent.com/97666287/207776701-4e5a98a4-85f1-4f99-b4d9-e1c49a767cb2.mp4

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Rishav1707 Nice Work. Add comments to your HTML and JS code.

**Comment by Rishav1707** [comment]
> @Rishav1707 Nice Work. Add comments to your HTML and JS code.

Done @utkarsh006

**Comment by utkarsh006** [comment]
Comments in html are not as // but like

**Comment by Rishav1707** [comment]
Ok

**Comment by Rishav1707** [comment]
> Comments in html are not as // but like `<!-- text here -->`

Done @utkarsh006

**Comment by utkarsh006** [comment]
@Rishav1707 Add working video in README file.

**Comment by Rishav1707** [comment]
I am unable to add working video in README file.
Please tell me how to insert MP4 video in README file.
I am trying to copy and pasting but it doesn't apply in README file.

**Comment by Rishav1707** [comment]
> I am unable to add working video in README file. Please tell me how to insert MP4 video in README file. I am trying to copy and pasting but it doesn't apply in README file.

@utkarsh006 Tell me how to insert video?

**Comment by utkarsh006** [comment]
@Rishav1707 Click on Attach files by dragging and upload a video from your system.

image

**Comment by Rishav1707** [comment]
> @Rishav1707 Add working video in README file.

Done, and thank you @utkarsh006 for helping me out.

**Comment by utkarsh006** [comment]
LGTM ⭐ NICE WORK

**Comment by Rishav1707** [comment]
> LGTM ⭐ NICE WORK

Thank you @utkarsh006

**Pull request merged**
