### PR TITLE
Adding Loan Calculator

### PR DESCRIPTION
**Pull request by Suryansh1720001**
Hello @Shweta2024 
**I added the Loan Calculator**
The main objective of this project is to calculate and displays the results for monthly payment, total payment, and total interest according to loan amount interest rate, and years to repay.

## Related Issue 
Issue no. #168 
Project name- Loan Calculator

## Describe Changes
✅ Added the project
✅ Added the comments 
✅ Read the Contributing Guideline
✅ I have starred the repo
✅ Added the Demo video in the Readme file
✅ Tech Stack added in Readme file

## Screenshot

image

## Demo Video 

https://user-images.githubusercontent.com/85965606/210969152-40d2a996-e8ad-498d-8c23-38efa33eb6c5.mp4

### CODE REVIEW

**Comment by Suryansh1720001** [comment]
@Shweta2024 
Kindle merge this issue 
Thank you

**Review by Shweta2024 — CHANGES_REQUESTED** [review]
the link to the demo video in the readme isn't working.
image

**Comment by Suryansh1720001** [comment]
@Shweta2024 
Now check, I removed the video link because of the time issue of kwoc, or I could not handle the issue due to a folder path problem. And yes video is present in the files.
Now kindly merge it as kwoc last date is 6/01/23.
Thank you.

**Comment by Shweta2024** [comment]
@Suryansh1720001 add the demo video in the readme.

**Comment by Suryansh1720001** [comment]
@Shweta2024 
I have added the demo video. Please check it and merge it accordingly.
Thank you

**Pull request merged**
