### PR TITLE
Added New Project

### PR DESCRIPTION
**Pull request by royalpinto007**
## Related Issue
No Issues as such, I have just added a new project for the existing repo.

### Describe Changes
Clock was a missing minor project in the repo, so I added it to make sure that it is not left :)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@royalpinto007 Follow the contributing guidelines if you want PR to get merged.

**Comment by royalpinto007** [comment]
Sure, I will look into it. 
Thanks for the info!

**Comment by utkarsh006** [comment]
@royalpinto007 Mention your changes in detail. It's not clear from the PR that what changes it brings to our repo.

**Comment by utkarsh006** [comment]
@royalpinto007 What's this?
Screenshot (277)

**Comment by royalpinto007** [comment]
I added a folder with 5 files in it, I am not sure that why it is showing just like this and not the files that I have added even though it shows that everything is up to date when I push it

**Comment by utkarsh006** [comment]
@royalpinto007 Try to do commits again in your branch because if the files changed are not visible, PR won't get merged.

**Pull request closed without merging**
