### PR TITLE
Music player

### PR DESCRIPTION
**Pull request by nikhilsrv**
## Related Issue
 
#105 

### Describe Changes

Added music player app with a visualizer

### Checklist:

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
Screenshot (502)

Screenshot (503)

### CODE REVIEW

**Comment by nikhilsrv** [comment]
@Shweta2024 @utkarsh006 please review my pull request.

**Comment by utkarsh006** [comment]
@nikhilsrv Rename the file ```1300.css``` with an appropriate name. Also, don't you have Html file in your project? Include that also.

**Comment by nikhilsrv** [comment]
@utkarsh006 I have changed the name and also added comment in that file,is it fine?

**Comment by utkarsh006** [comment]
@nikhilsrv Yes pretty much good. LGTM ⭐

**Pull request merged**
