### PR TITLE
Dictionary65

### PR DESCRIPTION
**Pull request by madeupgalaxy**
## Related issue 
Dictionary #65 

## Describe Changes
Created a Dictionary using HTML, CSS and JavaScript

## Checklist

- [x] 👨‍💻 My code follows the code style of this project.
- [x] ✌️All new and existing tests passed.
- [x] 🌟 I have starred the repository
- [x] 🙂 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

## What types of changes does your code introduce?
- [x] New feature (non-breaking change which adds functionality)

## Guidelines followed ?
- [x] Completed the project as per guidelines given. 
- [x] Created a detailed Readme.md file with a video sample.
- [x] Completed the Project within the time limit.

## Screenshots

Dictionary

### CODE REVIEW

**Comment by utkarsh006** [comment]
@madeupgalaxy Rename the file with proper meaningful names and add comments to your code.

**Comment by madeupgalaxy** [comment]
Have made necessary changes. Dictionary API allows voice output too but I couldn't work that out. And due to time restrictions have presented the best of my work.

> @madeupgalaxy Rename the file with proper meaningful names and add comments to your code.

**Comment by madeupgalaxy** [comment]
> Have made necessary changes. Dictionary API allows voice output too but I couldn't work that out. And due to time restrictions have presented the best of my work.
> 
> > @madeupgalaxy Rename the file with proper meaningful names and add comments to your code.

**Comment by utkarsh006** [comment]
@madeupgalaxy Any updates?

**Comment by madeupgalaxy** [comment]
> Have made necessary changes. Dictionary API allows voice output too but I couldn't work that out. And due to time restrictions have presented the best of my work.
> 
> > @madeupgalaxy Rename the file with proper meaningful names and add comments to your code.
> 
> 

@utkarsh006  I added comments and renamed the files 3 days ago😅. 
I thought you were busy with some work so didn't bother you 🙏
The quoted reply contains the updates.

**Review by Shweta2024 — APPROVED** [review]

**Comment by Shweta2024** [comment]
great work @madeupgalaxy 
LGTM🎉

**Pull request merged**
