### PR TITLE
css folder and images folder have been added.

### PR DESCRIPTION
**Pull request by dikshapadi**
## Related Issue
 

- Make attractive UI for BMI Calculator #2

Issue or task assigned was to add css to the BMI-calculator web app to make it look more attractive.
Specified changes were to add color , change font and align to center.

### Describe Changes

Added color , changed font , added bg image and aligned all text to the center.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
image

### CODE REVIEW

**Comment by Shweta2024** [comment]
> ## Related Issue
> * Make attractive UI for BMI Calculator [Make attractive UI for BMI Calculator #2](https://github.com/Shweta2024/JavaScript-Projects/issues/2)
> 
> Issue or task assigned was to add css to the BMI-calculator web app to make it look more attractive. Specified changes were to add color , change font and align to center.
> 
> ### Describe Changes
> Added color , changed font , added bg image and aligned all text to the center.
> 
> ### Checklist
> * [ ]  ✅ My code follows the code style of this project.
> * [ ]  🚩 All new and existing tests passed.
> * [ ]  🌟 I have starred the repo
> * [ ]  👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)
> 
> ### What types of changes does your code introduce?
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> ## Screenshots
> image

@dikshapadi please tick mark the checklist.

**Comment by Shweta2024** [comment]
@dikshapadi please tick mark the check list

**Comment by dikshapadi** [comment]
> @dikshapadi please tick mark the check list

done!

**Comment by Shweta2024** [comment]
> > @dikshapadi please tick mark the check list
> 
> done!

@dikshapadi 
Great work😄
LGTM🎉

**Pull request merged**
