### PR TITLE
text to speech converter

### PR DESCRIPTION
**Pull request by Riya14-dangra**
## Related Issue
 
 * #43  text to speech

### Describe Changes

I have made a text to speech convertor ,you can check below

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

* HTML code(to give the skeleton to our web page)

Screenshot (104)

* CSS code (to make UI more attractive)
Screenshot (105)

*  JS code
Screenshot (106)

I have added a README file to

* OUTPUT

https://user-images.githubusercontent.com/84792579/207635335-f89417ee-ebbf-487c-994a-11f1dac4d3a7.mp4

Hope you like it!!
Thank You:)

### CODE REVIEW

**Comment by Riya14-dangra** [comment]
> ## Related Issue
> * [Text-to-Speech #43](https://github.com/Shweta2024/JavaScript-Projects/issues/43)  text to speech
> 
> ### Describe Changes
> I have made a text to speech convertor ,you can check below
> 
> ### Checklist
> * [x]  ✅ My code follows the code style of this project.
> * [x]  🚩 All new and existing tests passed.
> * [x]  🌟 I have starred the repo
> * [x]  👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)
> 
> ### What types of changes does your code introduce?
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> ## Screenshots
> * HTML code(to give the skeleton to our web page)
> 
> Screenshot (104)
> 
> * CSS code (to make UI more attractive)
>   Screenshot (105)
> * JS code
>   Screenshot (106)
> 
> I have added a README file to
> 
> * OUTPUT
> 
>  Untitled.1.mp4 
> Hope you like it!! Thank You:)

@utkarsh006 Please have a look

**Comment by utkarsh006** [comment]
LGTM ⭐ Nice Work

**Comment by Riya14-dangra** [comment]
> LGTM star Nice Work

Thank you @utkarsh006 ✨thank you to helping me out👍

**Comment by utkarsh006** [comment]
@Riya14-dangra No issues we all are here to learn and grow. Just delete the branch after your PR gets merged.

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra No issues we all are here to learn and grow. Just delete the branch after your PR gets merged.

How to delete it can you please explain

**Comment by utkarsh006** [comment]
@Riya14-dangra When your PR will get merged, you will see an option to delete your branch. Just do it, it's good practice.
Try this out with your previous merged PR.

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra When your PR will get merged, you will see an option to delete your branch. Just do it, it's good practice. Try this out with your previous merged PR.

Yes I got it, done with previous one!! Thank you @utkarsh006

**Pull request merged**
