### PR TITLE
Changed UI for tic-tac-toe

### PR DESCRIPTION
**Pull request by DHRUVKHANDELWAL00**
## Related Issue

#132 

### Describe Changes

Changed some UI for tic-tac-toe by giving grid some gap.Also added Glassmorphism effect. Gave 'X' AND 'O' better colour.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
image

### CODE REVIEW

**Comment by Shweta2024** [comment]
what do you mean by "Hex Color Application"?
The issue title and the pr doesn't match. Also, the issue template isn't complete.

**Comment by DHRUVKHANDELWAL00** [comment]
@Shweta2024  i opened up issue to improve ui for toc-tac-toe but their @utkarsh006  told me to comment here and work on that same issue.

**Comment by Shweta2024** [comment]
> @Shweta2024 i opened up issue to improve ui for toc-tac-toe but their @utkarsh006 told me to comment here and work on that same issue.

comment on the issue that you created and put its issue number in the related issue section.

**Comment by DHRUVKHANDELWAL00** [comment]
@Shweta2024  i messed up....sorry

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Go through my 3 Reviews above and make the changes.

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006  which reviews?

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 See this !
Screenshot (307)

**Comment by Shweta2024** [comment]
@DHRUVKHANDELWAL00 resolve the merge conflicts.

**Comment by DHRUVKHANDELWAL00** [comment]
@Shweta2024  it says i dont have write access.

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Create a Fresh PR.

**Pull request closed without merging**
