### PR TITLE
Sign Up and Login Page

### PR DESCRIPTION
**Pull request by Riya14-dangra**
## Related Issue
SignUp and Login Page

### Describe Changes
I have made a attractive UI for it and make it responsive
#31 sign up and login form

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
Have a look please!!

https://user-images.githubusercontent.com/84792579/206618120-eaf28528-ecf2-4f9d-a345-19d5b81805c3.mp4

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Riya14-dangra Mention the issue.

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra Mention the issue. Add comments to the code. And make contributions from new branch.

Okay

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra Mention the issue. Add comments to the code. And make contributions from new branch.

@utkarsh006 Please merge this one from next contribution I make a new branch and currently I am mentioning the issue

**Comment by utkarsh006** [comment]
> 

Comments are not there. Read the contributing guidelines well.

**Comment by Riya14-dangra** [comment]
> > 
> 
> Comments are not there. Read the contributing guidelines well.
@utkarsh006 mam please have a look in code there are command & for this pull request please merge it I have made 2 contribution in the same way that was merged by shweta mam for this time merge it from onwards I will make a new branch

**Comment by utkarsh006** [comment]
@Riya14-dangra Shweta Merged it because she gives you a chance to improve upon your mistakes but you didn't. Hence, make a new branch and do the contribution. The PR has now been officially closed.

**Pull request closed without merging**
