### PR TITLE
Palindrome Checker

### PR DESCRIPTION
**Pull request by mansiyeole67**
issue number #128

### Describe 

Here, I made palindrome checker Javascript project.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

Screenshot (231)

### CODE REVIEW

**Comment by mansiyeole67** [comment]
here, i made palidrom checker project using javascript
Screenshot (231)

**Comment by utkarsh006** [comment]
@mansiyeole67 Mention issue number and complete the PR template.

**Comment by mansiyeole67** [comment]
i mention the issue number

**Review by utkarsh006 — COMMENTED** [review]
Add README file.

**Comment by Shweta2024** [comment]
@mansiyeole67 add a README file ASAP.

**Comment by utkarsh006** [comment]
@mansiyeole67 Any updates?

**Comment by Shweta2024** [comment]
@mansiyeole67 can you please bear the pain to reply?
Else your pr will be closed & issue will get unassigned.

**Comment by Shweta2024** [comment]
@utkarsh006 there are no updates, should I close the pr & unassign the issue?

**Comment by utkarsh006** [comment]
@Shweta2024 The PR has been officially closed.

**Pull request closed without merging**
