### PR TITLE
Fixed front UI of the weather website

### PR DESCRIPTION
**Pull request by PritamSarbajna**
## Related Issue
 
#23 Weather website UI improvement

### Describe Changes

I have changed the front ui of the weather website, you can check below.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

Screenshot (251)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@PritamSarbajna What changes have you done? Kindly mention it here, so that we can proceed further.

**Comment by PritamSarbajna** [comment]
> @PritamSarbajna What changes have you done? Kindly mention it here, so that we can proceed further.

Hello @utkarsh006 I have changed the following :

- Made changes index.html like adding classes and a few divs. But the base structure is still the same.
- I have created a static folder in which my style.css file is.
- From the basic html structure, I just added a dynamically changing bakground and a lot of modifications as you can see in the screenshot above.

**Comment by utkarsh006** [comment]
LGTM ⭐
@Shweta2024 Do Merge the PR.

**Comment by Shweta2024** [comment]
@PritamSarbajna great work!
LGTM🎉

**Pull request merged**
