### PR TITLE
alarm clock added

### PR DESCRIPTION
**Pull request by Riya14-dangra**
## Related Issue
 
*  #102 

### Describe Changes

I have added an alarm clock, you can check below

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### OUTPUT
https://user-images.githubusercontent.com/84792579/210193650-cfd29191-5c52-4540-88c3-105c22346ef8.mp4

Hope you like it!!
Thank you:)

### CODE REVIEW

**Comment by Riya14-dangra** [comment]
@Shweta2024 & @utkarsh006 please have a look

**Comment by utkarsh006** [comment]
@Riya14-dangra Do as mentioned in the Review and attach only output screenshots to the PR template.

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra Do as mentioned in the Review and attach only output screenshots to the PR template.

Done:)

**Comment by utkarsh006** [comment]
@Riya14-dangra Go to your html file here and then to files changed, there will be a Review, do as mentioned.

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra Go to your html file here and then to files changed, there will be a Review, do as mentioned.

@utkarsh006  & @Shweta2024  changes done please have a look

**Comment by Riya14-dangra** [comment]
> > @Riya14-dangra Go to your html file here and then to files changed, there will be a Review, do as mentioned.
> 
> @utkarsh006 & @Shweta2024 changes done please have a look

@Shweta2024 please have a look

**Review by Shweta2024 — CHANGES_REQUESTED** [review]
correct the spelling of alarm in the readme

**Comment by Riya14-dangra** [comment]
> correct the spelling of alarm in the readme



> correct the spelling of alarm in the readme

Done please have a look

**Pull request merged**
