### PR TITLE
Add Notes Taking App

### PR DESCRIPTION
**Pull request by SattyamSamania**
## Related Issue
 
#147

### Describe Changes

- I have created a Notes Taking App using HTML,  CSS and Javascript.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
Screenshot (277)

### CODE REVIEW

**Comment by SattyamSamania** [comment]
Here is the Video Link: 

https://user-images.githubusercontent.com/67833888/209654690-cbc62fbb-2108-418b-a4f1-95d42a960af9.mp4

**Comment by utkarsh006** [comment]
@SattyamSamania Remove the unused code in index.html

**Comment by SattyamSamania** [comment]
> @SattyamSamania Remove the unused code in index.html

@utkarsh006 Done. You can check now.

**Comment by utkarsh006** [comment]
@SattyamSamania Follow Guideline 6.

**Pull request closed without merging**
