### PR TITLE
Bad button

### PR DESCRIPTION
**Pull request by sakshipratap**
## Related Issue

#56
Changes to the project "Bad-Button" 

Existing UI has a grey background,  a "click me" text written on the button, simple display screen.

### Describe Changes
I've updated more of CSS and html for adding text in the existing file. Added a moving Illusory background, a non disappearing text with disappearing particles as an animation, glowing border around the button and an evil eye background to it.

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
ss1

https://user-images.githubusercontent.com/91501549/207810435-4e5c4184-cede-4051-aff3-d5ee5c28ffe3.mp4

https://user-images.githubusercontent.com/91501549/207811722-2a1ff814-60a7-4646-919b-3eec2904f777.mp4

This was the original one: 
ssOriginal

### CODE REVIEW

**Comment by utkarsh006** [comment]
@sakshipratap Mention the issue number and tell to which project you're doing the changes.

**Comment by sakshipratap** [comment]
Changes done 👍

**Comment by sakshipratap** [comment]
> @sakshipratap Mention the issue number and tell to which project you're doing the changes.

Changes done 👍

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
