### PR TITLE
ADDED FAVICON AND A BETTER BACKGROUND IMAGE

### PR DESCRIPTION
**Pull request by DHRUVKHANDELWAL00**
## Related Issue
 
Adding Favicon to BMI calculator and adding UI TO THE HOME PAGE AND RESULT PAGE #60

### Describe Changes

Added a favicon to the page and a better background image to it. 

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots

ssx

### CODE REVIEW

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Complete the PR template. Fill in the checkboxes. Add a working video here in the PR template of your project.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @utkarsh006  can u elaborate where u need the video? can i give it here?

**Comment by DHRUVKHANDELWAL00** [comment]
[7c99127a-fa0c-49bb-887d-4ee03e857020.webm](https://user-images.githubusercontent.com/99539203/207781304-d1c58e70-7744-481c-9fb8-899f73fbe29d.webm)

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Kindly see the guidelines where to upload a video.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @utkarsh006 , should i make a new pr to add readme.md file? or make changes in existing one please can u guide me how to do it.

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Don't do that, commit changes to this branch only.

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006 ok

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006 Done

**Comment by utkarsh006** [comment]
> @DHRUVKHANDELWAL00 Complete the PR template. Fill in the checkboxes. Add a working video here in the PR template of your project.

Complete the PR template by filling checkboxes.

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006 all checkboxes have been filled....which one are u talking about?

**Comment by utkarsh006** [comment]
> @utkarsh006 all checkboxes have been filled....which one are u talking about?

Do like this [x]

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006 done

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
