### PR TITLE
login signUp page added

### PR DESCRIPTION
**Pull request by Riya14-dangra**
## Related Issue
 
Login signup page 
#31 

### Describe Changes

i have make a responsive login and signup form 

### Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 I have starred the repo
- [x] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots
Please have a look

https://user-images.githubusercontent.com/84792579/206858628-3dba1a91-eaf0-4019-bb4b-44ba56070d44.mp4

Hope you like it 
Thank you!!

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Riya14-dangra If you haven't starred the repo why did you marked it as checked?

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra If you haven't starred the repo why did you marked it as checked? Add Comments to your project and make a README file inside it.

@utkarsh006 sir i have starred the repo. Comments are already there in a code

**Comment by utkarsh006** [comment]
@Riya14-dangra What's your css and JS code is doing? Explain with comments.

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra What's your css and JS code is doing? Explain with comments.

sir class name itself explaining the work done by each div and  in js their is only a toggle function nothing much more and its not a complete website to comment the specific div or sections of a website

**Pull request closed without merging**
