### PR TITLE
Replaced text with drop-down menu

### PR DESCRIPTION
**Pull request by SattyamSamania**
## Related Issue
 
- Fixed issue #1   

### Describe Changes

- Created drop-down menu to select list of cities to check weather.

### Checklist

- [ x] ✅ My code follows the code style of this project.
- [x ] 🚩 All new and existing tests passed.
- [x ] 🌟 I have starred the repo
- [x ] 👀 I have read the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md)

### What types of changes does your code introduce?
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshots -
Screenshot (263)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@SattyamSamania Good Job Satyam 🧡 Just tick mark all the boxes in PR template, mention issue number, and add working video of your project in README file.

**Comment by SattyamSamania** [comment]
> @SattyamSamania Good Job Satyam 🧡 Just tick mark all the boxes in PR template, mention issue number, and add working video of your project in README file.

@utkarsh006 Sure, I will tick mark the boxes and mention issue number. But I think I have added video in the Readme file. If it's not showing I will add again.

**Comment by utkarsh006** [comment]
@SattyamSamania Resolve Merge conflicts and add working video here of your project.

**Comment by SattyamSamania** [comment]
> @SattyamSamania Resolve Merge conflicts and add working video here of your project.

@utkarsh006 should I add video here? I think I have added video in the Readme file. I will definitely resolve merge conflicts by today itself.

**Comment by utkarsh006** [comment]
@SattyamSamania I think you have created 2 PR's for one issue.

**Comment by utkarsh006** [comment]
@SattyamSamania Attach video of your project and close one PR that you have created extra for this issue.

**Comment by SattyamSamania** [comment]
> LGTM ⭐ Nice Work

Thank you @utkarsh006 and @Shweta2024 for your constant support and helping me. Looking forward for more contributions.

**Comment by utkarsh006** [comment]
@SattyamSamania No issues buddy. We are Happy to help you out. You are our first contributor who created the first issue.

**Comment by Shweta2024** [comment]
great work @SattyamSamania 
LGTM😄🎉

**Comment by SattyamSamania** [comment]
> great work @SattyamSamania 
> LGTM😄🎉

Thank you helping me 😊

**Pull request merged**
