### PR TITLE
Add Live Clock

### PR DESCRIPTION
**Pull request by Suryansh1720001**
Response to issue #53 
Hello, @utkarsh006 @Shweta2024 
I added the Live clock project of Java-script. After review, please merge it accordingly. 
Thank you

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Suryansh1720001 Add comments to your code.

**Comment by utkarsh006** [comment]
@Suryansh1720001 What's the update?

**Comment by Suryansh1720001** [comment]
Hello @utkarsh006 
Need a little bit of time. I will PR/commit the update shortly.

**Comment by Suryansh1720001** [comment]
Hello @utkarsh006,
Now you can review it and merge it accordingly.
Thank you.

**Comment by Shweta2024** [comment]
@Suryansh1720001 kindly use the pr template.

**Comment by Suryansh1720001** [comment]
**I added the Live clock project of Java-script. It is a live clock, you can watch it in your browser window.**

## Related Issue 
Issue no. #53 
Project name- Live Clock

## Describe Changes
✅ Added the project
✅ Added the comments 
✅ Read the Contributing Guideline
✅ I have starred the repo


## Screenshot
image

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
